# jwt config
jwt:
  header: Auth-Token
  issuer: www.yukens.com
  key: kisszpy
  context: userId
# mysql config
mysql:
  username: root
  password: password
  host: 10.6.2.12
  port: 3307
# redis config
redis:
  host: 172.20.103.11
  port: 6383
  db: 0
  pass: poiu@1234
# mongo
mongo:
  uri: mongodb://user:Test#1234@172.20.30.23:8635,172.20.30.81:8635/seagull?authSource=admin&replicaSet=replica
# file upload config
upload:
  excel:
    path: /tmp/excel/