# jwt config
jwt:
  header: Auth-Token
  issuer: www.yukens.com
  key: kisszpy
  context: userId
# mysql config
mysql:
  username: root
  password: Metro#79
  host: 127.0.0.1
  port: 3306
# file upload config
upload:
  excel:
    path: /tmp/excel/