# jwt config
jwt:
  header: Auth-Token
  issuer: www.yukens.com
  key: kisszpy
  context: userId
# mysql config
mysql:
  username: root
  password: password
  host: 10.6.2.12
  port: 3307
# redis config
redis:
  host: 172.20.103.11
  port: 6383
  db: 0
  pass: poiu@1234
# file upload config
upload:
  excel:
    path: /tmp/excel/